version: "3.8"

networks:
  sonarnet:
    driver: bridge

services:
  sonarqube:
    image: sonarqube
    ports:
      - "9000:9000"
    networks:
      - sonarnet
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - ./volume/sonarqube/conf:/opt/sonarqube/conf
      - ./volume/sonarqube/logs:/opt/sonarqube/logs
      - ./volume/sonarqube/temp:/opt/sonarqube/temp
      - ./volume/sonarqube/data:/opt/sonarqube/data
      - ./volume/sonarqube/extensions:/opt/sonarqube/extensions
      - ./volume/sonarqube/bundled_plugins:/opt/sonarqube/lib/bundled-plugins

  db:
    image: postgres
    networks:
      - sonarnet
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - ./volume/postgresql:/var/lib/postgresql
      - ./volume/postgresql_data:/var/lib/postgresql/data