version: '3.7'
services:
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATBASE: my-database
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: Mongo@123
    ports:
      - 27017:27017
    volumes:
      - ./volume:/data/db
volumes:
  mongodb_data_container: